### ISSUE TITLE
Improve REST docs

### ISSUE THREAD

**Issue by x1unix** [erafaelmanuel/cshop#1]
I recommend using [Swagger](https://swagger.io/) or [Postman](https://www.getpostman.com/) to generate API documentation.

**Postman** allows testing your API and generate&public documentation.

**Swagger** allows to declare your API and generate code (scaffolding) and generate docs.

Personally, I use **Postman**.

Good luck :)

**Comment by erafaelmanuel** [comment]
Thank you for your suggestions. These are exactly the tools I need

**Comment by x1unix** [comment]
@erafaelmanuel, you're welcome 😄
